import "../styles/index.scss"
import type { Metadata } from "next"
import Head from "next/head"
import Providers from "./store/provider"

export const metadata: Metadata = {
  title: "Crypto Watch App",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="/icon.png" />
      </Head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
